services:
  screenshoter:
    image: "mingalevme/screenshoter"
    ports:
      - 127.0.0.1:3000:8080
    restart: unless-stopped
  api:
    depends_on: ["screenshoter"]
    build: .
    ports:
      - 127.0.0.1:4040:5000
    restart: unless-stopped
